sfSympalSite:
  actAs: [sfSympalRecordTemplate]
  columns:
    theme: string(255)
    title:
      type: string(255)
      notnull: true
    description:
      type: clob
      notnull: true
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)

sfSympalRedirect:
  actAs: [sfSympalRecordTemplate]
  columns:
    site_id:
      type: integer
      notnull: true
    source:
      type: string(255)
      notnull: true
    destination: string(255)
    content_id: integer
  relations:
    Site:
      local: site_id
      class: sfSympalSite
      onDelete: CASCADE
      foreignAlias: Redirects
    Content:
      local: content_id
      class: sfSympalContent
      onDelete: CASCADE
      foreignAlias: Redirects

sfSympalContent:
  actAs: [Timestampable, sfSympalRecordTemplate]
  columns:
    site_id:
      type: integer
      notnull: true
    content_type_id:
      type: integer
      notnull: true
    last_updated_by_id: integer
    created_by_id:
      type: integer
      notnull: true
    date_published: timestamp
    custom_path: string(255)
    theme: string(255)
    template: string(255)
    module: string(255)
    action: string(255)
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)
    i18n_slug: string(255)
  indexes:
    date_published:
      fields: [date_published]
  relations:
    LastUpdatedBy:
      class: <?php echo sfSympalConfig::get('user_model') ?> 
      local: last_updated_by_id
      foreignAlias: LastUpdatedContent
      onDelete: SET NULL
    CreatedBy:
      class: <?php echo sfSympalConfig::get('user_model') ?> 
      local: created_by_id
      foreignAlias: CreatedContent
      onDelete: CASCADE
    Site:
      local: site_id
      class: sfSympalSite
      onDelete: CASCADE
      foreignAlias: Content
    Type:
      local: content_type_id
      class: sfSympalContentType
      onDelete: CASCADE
      foreignAlias: Content
    Groups:
      class: <?php echo sfSympalConfig::get('group_model') ?> 
      local: content_id
      foreign: group_id
      refClass: sfSympalContentGroup
      foreignAlias: Content
    Slots:
      class: sfSympalContentSlot
      refClass: sfSympalContentSlotRef
      local: content_id
      foreign: content_slot_id
      foreignAlias: Content
    Links:
      class: sfSympalContent
      refClass: sfSympalContentLink
      local: content_id
      foreign: linked_content_id
      autoComplete: false

sfSympalContentLink:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      filter: false
      form: false
  columns:
    content_id:
      type: integer
      primary: true
    linked_content_id:
      type: integer
      primary: true
  relations:
    Content:
      class: sfSympalContent
      local: content_id
      foreign: id
      onDelete: CASCADE
      foreignAlias: sfSympalContentLinks
    LinkedContent:
      class: sfSympalContent
      local: linked_content_id
      foreign: id
      onDelete: CASCADE
      foreignAlias: sfSympalContentLinks

sfSympalContentType:
  actAs: [sfSympalRecordTemplate]
  columns:
    name:
      type: string(255)
      notnull: true
    description: clob
    label:
      type: string(255)
      notnull: true
    plugin_name:
      type: string(255)
      notnull: true
    default_path: string(255)
    theme: string(255)
    template: string(255)
    module: string(255)
    action: string(255)
  indexes:
    content_type_name:
      fields: [name]

sfSympalContentSlot:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      filter: false
  columns:
    is_column:
      type: boolean
      default: false
    render_function: string(255)
    name:
      type: string(255)
      notnull: true
    type:
      type: string(255)
      notnull: true
    value: clob
  indexes:
    name:
      fields: [name]
    type:
      fields: [type]

sfSympalContentSlotRef:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_slot_id:
      type: integer
      primary: true
    content_id:
      type: integer
      primary: true
  relations:
    Slot:
      class: sfSympalContentSlot
      local: content_slot_id
      foreignAlias: ContentSlotRefs
      onDelete: CASCADE
    Content:
      class: sfSympalContent
      local: content_id
      foreignAlias: ContentSlotRefs
      onDelete: CASCADE

sfSympalContentGroup:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_id:
      primary: true
      type: integer
    group_id:
      primary: true
      type: integer
  relations:
    Content:
      local: content_id
      class: sfSympalContent
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Group:
      class: <?php echo sfSympalConfig::get('group_model') ?> 
      local: group_id
      foreignAlias: ContentGroups
      onDelete: CASCADE